-- CampusMart Supabase Schema Setup
-- Run this in your Supabase SQL Editor

-- 1. Profiles Table
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  whatsapp TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Products Table
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  price DECIMAL,
  condition TEXT,
  location TEXT,
  image_url TEXT,
  seller_id uuid REFERENCES public.profiles(id),
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Messages Table
CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name TEXT,
  receiver_name TEXT,
  product_title TEXT,
  message_content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Wishlists Table
CREATE TABLE public.wishlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id),
  product_id BIGINT REFERENCES public.products(id),
  UNIQUE(user_id, product_id)
);

-- 5. Activity Logs (for Admin Dashboard Analytics)
CREATE TABLE public.activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id),
  user_email TEXT, -- Store email for quick admin reference
  activity_type TEXT NOT NULL, -- e.g., 'login', 'view_product', 'create_listing', 'logout'
  details JSONB, -- Additional context (e.g., product_id, category)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create index for faster admin queries
CREATE INDEX idx_activity_logs_created_at ON public.activity_logs(created_at DESC);
CREATE INDEX idx_activity_logs_user_email ON public.activity_logs(user_email);
CREATE INDEX idx_activity_logs_type ON public.activity_logs(activity_type);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies (Simple versions for testing)
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Anyone can create products" ON public.products FOR INSERT WITH CHECK (true);

CREATE POLICY "Messages are viewable by sender or receiver" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Anyone can send messages" ON public.messages FOR INSERT WITH CHECK (true);

-- 4. Wishlists Policies
CREATE POLICY "Wishlists are viewable by owner" ON public.wishlists FOR SELECT USING (true);
CREATE POLICY "Anyone can add to wishlist" ON public.wishlists FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can remove from wishlist" ON public.wishlists FOR DELETE USING (true);

-- 5. Activity Logs Policies
CREATE POLICY "Activity logs are viewable by everyone" ON public.activity_logs FOR SELECT USING (true);
CREATE POLICY "Anyone can log activity" ON public.activity_logs FOR INSERT WITH CHECK (true);
